name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.12

      - name: Add Bindata
        run: go get github.com/jteeuwen/go-bindata
      - name: Add a Bindata Assetfs
        run: go get github.com/elazarl/go-bindata-assetfs
      - name : Database test
        run : |
          echo "Run Cockroachdb"
          mkdir build
          sudo curl -L https://binaries.cockroachdb.com/cockroach-v21.2.5.linux-amd64.tgz | tar  xvz
          sudo mv -f cockroach-v21.2.5.linux-amd64/cockroach ./build
          cd cockroach-v21.2.5.linux-amd64/cockroach
          ls -lh
